### ISSUE TITLE
Spherical harmonic data is not saved on export: what does it mean ? 

### ISSUE THREAD

**Issue by cyrilpreiss** [playcanvas/super-splat#7]
Sorry but does this limitation mean ?

**Comment by slimbuck** [comment]
Instead of having just a single colour value, each gaussian splat can have a spherical harmonic instead. A spherical harmonic stores colour values for all directions on a sphere. Individual splats can then be rendered with different colours depending on the direction you're viewing them from. This means the scene can have "view specific" effects, like shiny reflections on car surfaces and windows and puddles etc.

We are currently not loading and saving all the spherical harmonic data because it is large and the results we've seen so far were good enough using just a single colour per splat.

However these are early days and we will most likely be adding support for full spherical harmonics in future!

**Comment by slimbuck** [comment]
Closing
